[package]
name = "hello-http"
version = "0.1.0"
authors = ["Saša Pul <sasa.pul@freska.fi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
